### ISSUE TITLE
zookeeper-quorum 

### ISSUE THREAD

**Issue by patsevanton** [andrewrothstein/ansible-zookeeper-cluster#6]
Hello!

[zookeeper]
host1 zookeeper_myid=1
host2 zookeeper_myid=2
host3 zookeeper_myid=3
....
hostN zookeeper_myid=N

[zookeeper-quorum]
host[1:N] or host[1:N-1] ?
Thanks!

**Comment by andrewrothstein** [comment]
I fixed the documentation. I was incorrectly presuming host[1:7] included the host labeled host7. it doesn't. I corrected the example to specify [0:7] and have a `host0 zookeeper_my_id=0` in inventory.

In your example if your hosts are named host1 ... host7 then your quorum would be host[1:8].

**Comment by paul42** [comment]
quick q: how would this look in a .yaml file? I'm still learning ansible/yaml, so thank you for your work!
```
dev_zookeeper:
  hosts:
    zk-1:
      ansible_ssh_host: 10.x.x.x
      zookeeper_myid: 1     
    zk-2:
      ansible_ssh_host: 10.x.x.x
      zookeeper_myid: 2
    zk-3:
      ansible_ssh_host: 10.x.x.x
      zookeeper_myid: 3
#not certain how to represent the zookeeper-quorum tag in .yaml
zookeeper-quorum:
    host[1:3]#?
```
